### ISSUE TITLE
TplBlock behaviour

### ISSUE THREAD

**Issue by Zigazou** [gnieark/tplBlock#4]
Hi !

What is TplBlock supposed to do when it encounters a template like this:

            Bhah blah wpooie456
            
                have to be shown
            
                SHOULD be shown
            
                WONT to be shown
            

It shouldn’t normally accept it (but it does!).
So what is it supposed to output?

**Comment by gnieark** [comment]
(je suis sur mon tél et mon correcteur est galère pour saisir en anglais.)

Ce cas là est une erreur. La gestion de cette erreur n'est pas encore implémentée.

Je comptais implémenter deux modes à la class "strict" par défaut (qui sort en erreur à la moindre erreur)
Strict=off qui efface les marques de templates restantes et genere ce qu'il peut générer sans sortir en erreur.

**Comment by gnieark** [comment]
PS, même principe pour des simples variables de template qui n'ont été appelées.

Comportement par défaut remplacer par une chaine vide
